#
# Makefile for the Hi-Fi provenance system
#
# Copyright (C) 2013 The Pennsylvania State University
# Systems and Internet Infrastructure Security Laboratory
#
# Author: Devin J. Pohly <djpohly@cse.psu.edu>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2 of the License.
#

obj-$(CONFIG_SECURITY_HIFI) := hifi.o

hifi-y := hifi_lsm.o
